# Generated by Django 4.2 on 2023-05-02 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_img_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='owner',
        ),
        migrations.AddField(
            model_name='product',
            name='favorite_list',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
