# Generated by Django 4.2 on 2023-05-02 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_owner_product_favorite_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='favorite_list',
        ),
    ]
